### ISSUE TITLE
Adcoin walled/payment

### ISSUE THREAD

**Issue by jkerssies91** [adcoin-project/AdCoin#1]
Hello,

My adcoin walled is doing weard. I download it from getadcoin.com. it won't sync with the network. It says 2 hours left for a day. I closed the walled and re opened it and know it's 9 hours left for a while.

My seccond problem is that I payed 50 euro to receieve some coins but didn't get anything. It's more then 24 hours ago.

Could somebody help me?

**Comment by rispel** [comment]
Hi @jkerssies91 

Synching is normally a sign of not enough miners on the network and not wallet related. I think you should send an e-mail to them or give them a call. There is contact information on the website.

**Comment by Ketkew23** [comment]
I talk to the Adcoin guy(s) on FB and they confirmed what you stated. The only thing what you can do is wait. The coins will come for sure. In my scenario it took 2 days.
