### ISSUE TITLE
CTRL + H

### ISSUE THREAD

**Issue by iliaselmatani** [adcoin-project/AdCoin#23]
Guys,

The code and other files in this repository should be reviewed. What is see is a quick and dirty search and replace work (code forked from LiteCoin). References to dead links such as adcoin.org in stead of getadcoin.com. Even the new issue template (see below) should be modified. Enough work for you guys. I started to help you out by some PR's. 

Keep on going.

-Ilias 

Personal ; can you please remove me from the banlist on telegram (@adcoinacc)? Not sure why you banned me.

--

This issue tracker is only for technical issues related to adcoin-core.

General adcoin questions and/or support requests and are best directed to the [adcointalk.io forums](https://adcointalk.io/).

For reporting security issues, please contact the AdCoin developers on the #adcoin-dev Freenode IRC channel or alternatively you can email us at contact@adcoin.org.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of adcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by getadcoin** [comment]
Hello iliaselmatani,

Agreed :) We focused on functionality over the documentation. We needed stable builds with DGW and SegWit integrated + good builds, which had some issues in the standard LTC code (also send a PR to Litecoin). We have limited resources to update the GH at this moment as we are pushing on application development.

Thank you for the PR and we will schedule time to focus on this after we manage to get the first real world use cases up and running.

P.s. You were banned by one of the moderators, a developer just unbanned you.
